const USERS_GIT_SUCCESS = "USERS_GIT_SUCCESS";
const USERS_GIT_ERROR = "USERS_GIT_ERROR";
const USERS_GIT_DETAIL_SUCCESS = "USERS_GIT_DETAIL_SUCCESS";
const USERS_GIT_DETAIL_ERROR = "USERS_GIT_DETAIL_ERROR";
const INITIAL_RENDER = "INITIAL_RENDER";
const LOADING = "LOADING";

const TYPE = {
  LOADING,
  INITIAL_RENDER,
  USERS_GIT_SUCCESS,
  USERS_GIT_ERROR,
  USERS_GIT_DETAIL_SUCCESS,
  USERS_GIT_DETAIL_ERROR
};

export default TYPE;
